name: Create or Update Dev to Main PR

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  create_or_update_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Fetch all history so we can compare branches and generate a changelog
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Changelog Generator
        run: npm install -g conventional-changelog-cli

      - name: Find Existing Pull Request
        id: find_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --base main --head dev --state open --json number -q '.[0].number' || echo "")
          if [ -n "$PR_NUMBER" ]; then
            echo "Found existing PR: #$PR_NUMBER"
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT
          else
            echo "No open PR found. Will create one."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate PR Title and Body
        id: generate_content
        run: |
          # Generate Title
          VERSION_INFO=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.1")
          echo "title=chore(release): ${VERSION_INFO}" >> $GITHUB_OUTPUT

          # Generate Body
          # This command creates a changelog for all commits that are in 'dev' but not in 'main'
          BODY_CONTENT=$(conventional-changelog --preset angular --commit-path . --compare-url "https://github.com/${{ github.repository }}/compare/main...dev")
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo -e "This PR is automatically generated and contains the latest changes from the dev branch.\n\n$BODY_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create or Update Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ steps.find_pr.outputs.exists }}" == "true" ]; then
            echo "Updating existing PR #${{ steps.find_pr.outputs.number }}"
            gh pr edit ${{ steps.find_pr.outputs.number }} \
              --title "${{ steps.generate_content.outputs.title }}" \
              --body-file - <<-EOF
              ${{ steps.generate_content.outputs.body }}
              EOF
          else
            echo "Creating new PR"
            gh pr create \
              --base main \
              --head dev \
              --title "${{ steps.generate_content.outputs.title }}" \
              --body-file - <<-EOF
              ${{ steps.generate_content.outputs.body }}
              EOF
          fi
