name: Create Dev to Main PR

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Fetch all history and tags for git-describe
          fetch-depth: 0

      - name: Check for Existing Pull Request
        id: check_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh pr list --base main --head dev --state open | grep -q '.'; then
            echo "An open PR from dev to main already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "No open PR found. Will create one."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Pull Request Title
        id: generate_title
        if: steps.check_pr.outputs.exists == 'false'
        run: |
          # Use the latest tag description, or 'v0.0.1' as a fallback.
          VERSION_INFO=$(git describe --tags 2>/dev/null || echo "v0.0.1")
          echo "title=chore(release): based on ${VERSION_INFO}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check_pr.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head dev \
            --title "${{ steps.generate_title.outputs.title }}" \
            --body "This PR is automatically generated and contains the latest changes from the dev branch."
